permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Demon Li
  email: demonli7452@gmail.com
  link: http://demon7452.github.io/
  weibo: 
  github: https://github.com/demon7452
  music: 
  linkedin: 

# 站点信息
title: Hello World
description: My personal blog
url: http://demon7452.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/icon.jpg
favicon: /public/img/icon.jpg
background: /public/img/background.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - ACG
  - Linux

# 中文本地化
locals:
  tags: 标签
  about: About
  newest: 最新文章
  archive: 归档
