# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hello World
email: demonli7452@gmail.com
description: >- # this means to ignore newlines
  My personal blog,From Xiong Li.

baseurl: "" # the subpath of your site, e.g. /blog
url: http://demon7452.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
rss_url: /pages/atom.xml

# 作者信息
author:
  name: Xiong Li
  email: demonli7452@gmail.com
  link: http://demon7452.github.io/
  weibo: http://weibo.com/p/1005053735019684/home
  github: https://github.com/demon7452
  music: http://music.163.com/#/user/home?id=61596017
  linkedin: http://demon7452.github.io/Resume/

twitter_username: demon7452
github_username:  demon7452

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


permalink: /:year/:month/:day/:title.html
gems: [jekyll-paginate]
paginate: 10
highlighter: rouge
redcarpet:
  extensions: [ "fenced_code_blocks",
                "hard_wrap",
                "autolink",
                "tables",
                "strikethrough",
                "with_toc_data",
                "highlight",
                "prettify",
                "no_intra_emphasis"]


# gavatar头像及Favicon
gavatar: /public/img/icon.jpg
favicon: /public/img/icon.jpg
background: /public/img/background.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: demon7452

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - ACG
  - vr

# 中文本地化
locals:
  tags: 标签
  about: About
  newest: 最新文章
  archive: 归档
